// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Task4.Data.DbContexts;

#nullable disable

namespace Task4.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Task4.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4896),
                            Email = "abdulloh@itransition.com",
                            LastLoginTime = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4898),
                            Name = "Abdulloh Axmadjonov",
                            Password = "1234",
                            Status = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4900),
                            Email = "p.lebedev@itransition.com",
                            LastLoginTime = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4901),
                            Name = "Pavel Lebedev",
                            Password = "1234",
                            Status = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4902),
                            Email = "risolass@gmail.com",
                            LastLoginTime = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4903),
                            Name = "Risolat Nurillaeva",
                            Password = "1234",
                            Status = 1
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4905),
                            Email = "jasur@icoud.com",
                            LastLoginTime = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4906),
                            Name = "Jasur Rasulov",
                            Password = "1234",
                            Status = 1
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4907),
                            Email = "normatov@gmail.com",
                            LastLoginTime = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4908),
                            Name = "Umar Normvatov",
                            Password = "1234",
                            Status = 1
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4909),
                            Email = "buggy@gmail.com",
                            LastLoginTime = new DateTime(2023, 5, 31, 13, 11, 59, 85, DateTimeKind.Utc).AddTicks(4910),
                            Name = "Buggy Anvarjonov",
                            Password = "1234",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
